twelve-monkeys
==============

:toc:
:toc-placement: preamble
:toclevels: 1
:project-artifact-name: twelve-monkeys

// Need some preamble to get TOC:
{empty}

image:https://img.shields.io/travis/marzelwidmer/twelve-monkeys.svg?style=flat-square["TravisCI", link="https://travis-ci.org/marzelwidmer/twelve-monkeys"]
image:https://circleci.com/gh/marzelwidmer/twelve-monkeys.svg?style=shield&circle-token=:circle-token["CircleCI", link="https://circleci.com/gh/marzelwidmer/twelve-monkeys"]
image:https://api.codacy.com/project/badge/Grade/f1b86eee772c4c7aaf65d2b896585365["Codacy code quality", link="https://www.codacy.com/app/marzelwidmer/twelve-monkeys?utm_source=github.com&utm_medium=referral&utm_content=marzelwidmer/twelve-monkeys&utm_campaign=Badge_Grade"]
image:https://coveralls.io/repos/github/marzelwidmer/twelve-monkeys/badge.svg?branch=develop["Coverage Status", link="https://coveralls.io/github/marzelwidmer/twelve-monkeys?branch=develop"]




[installation]
== Installation

:spring-boot-ref-guide: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/
:spring-boot-ref-guide-executable-jar: http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started-first-application-executable-jar


=== Build Application:
 $ mvn package

Copy the file {project-artifact-name}.jar anywhere on the server.
The JAR already contains the configuration for all available environments.
For further information please visit the  {spring-boot-ref-guide}[Spring Boot Reference Guide]

=== Start Application
==== Default Profile
Start application on command line. The _default_ profile supports a H2 datbase.
For more information please visit the {spring-boot-ref-guide-executable-jar}[Spring Boot Reference Guide] for further information.

    $ java -jar twelve-monkeys.jar

There are additional Spring profiles available.

==== Profiles
.Table -Dspring.profiles.active=

.Profiles
|===
|Profile |Environment |Database

|default
|dev
|H2

|development
|development
|Oracle
|===




==== SOAP Debug VM-Argument
    -Dcom.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.dump=true
    -Dcom.sun.xml.ws.transport.http.client.HttpTransportPipe.dump=true
    -Dcom.sun.xml.ws.transport.local.LocalTransportPipe.dump=true
    -Dcom.sun.xml.ws.transport.http.HttpAdapter.dump=true
    -Dcom.sun.xml.internal.ws.transport.http.HttpAdapter.dumpTreshold=10000

