# Spring
spring:
  profiles:
    active: dev
  application:
    name: 12monkeys-service
  # I18N (MessageSourceAutoConfiguration)
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: UTF-8



# Infos Build
info.build:
  artifact: @project.artifactId@
  name: @project.name@
  description: @project.description@
  version: @project.version@



# Management
management:
  address: ${server.address}
  port: ${server.port}
  context-path: /manage

# Endpoints
endpoints.health:
  enabled: true
  sensitive: false


# SOAP
soap:
  wsdl: classpath:wsdl/Tarif_v2_0.wsdl
  portname: TarifPort
  servicename: Tarif
  namespace: http://services.helsana.ch/spezialfunktionen/tarif/v2
  endpoint:
    #server: http://services.spfkern-test.hel.kko.ch
    server: http://services.spf-go-preprod.hel.kko.ch
    path: soa-infra/services/businessdomain_spezialfunktionen/Tarif_v2_ebs
    url: ${soap.endpoint.server}/${soap.endpoint.path}
    service: ${soap.endpoint.url}/Tarif


# Logging
logging:
  level.: warn
  level.org.springframework.boot: info
  level.org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: info

# Server
server:
  address: localhost
  port: 8080

# Tomcat
  tomcat:
    max-http-header-size: 16380
    compression: on
    compressableMimeTypes: application/json,application/xml,text/html,text/xml,text/plain